[config]
[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.foot]
input_path = './templates/foot-colors.ini'
output_path = '~/.config/foot/colors.ini'
